# Generated by Django 3.2.9 on 2021-11-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211103_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1.Banners'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '3.Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2.Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '4.Colors'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7.ProductAttributs'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': '6.Products'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '5.Sizes'},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_code',
        ),
    ]
