# Generated by Django 3.2.9 on 2021-11-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartorder_catorderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=150)),
                ('item', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '9.Cart Items',
            },
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '8.Orders'},
        ),
        migrations.DeleteModel(
            name='CatOrderItems',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartorder'),
        ),
    ]
